# ==========================================
# Docker Compose DESARROLLO
# ==========================================

version: '3.8'

services:
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: development
    image: ecoes-frontend:dev
    container_name: ecoes-frontend-dev
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=1
    volumes:
      # Mount código para desarrollo
      - .:/app
      - /app/node_modules  # Prevent overwriting node_modules
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - ecoes-dev-network
    command: ["flask", "run", "--host=0.0.0.0", "--port=5000", "--debug"]

  # Tailwind watcher para CSS en desarrollo
  tailwind-watcher:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: node-tools
    container_name: ecoes-tailwind-watcher
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    command: ["npm", "run", "dev"]
    networks:
      - ecoes-dev-network

networks:
  ecoes-dev-network:
    driver: bridge
